name: Tests
on: [push]

jobs:
  test_zemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - name: Build Ledger app
        run: |
          make
      - name: Install node and yarn
        run: |
          nvm install 14.4.0
          nvm use 14.4.0
          npm install -g yarn
      - name: Build/Install build js deps
        run: |
          nvm use 14.4.0
          make zemu_install
      - name: Run zemu tests
        run: |
          nvm use 14.4.0
          make zemu_test

  test_zemu_ledgeracio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14.4.0'
      - name: Install node + yarn
        run: |
          npm install -g yarn
      - name: Build/Install build js deps
        run: |
          make zemu_install
      - name: Build Ledger app
        run: |
          make build_ledgeracio
      - name: Run zemu tests for Ledgeracio app
        run: |
          COIN=Ledgeracio make zemu_test